Fixed populatedb order creation sometimes crashing
When a randomly selected user had no default billing address, populatedb command would crash for the following reason:
> Order does not have a billing address.

----
PaymentError: Order does not have a billing address.
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "saleor/core/management/commands/populatedb.py", line 104, in handle
    for msg in create_orders(20):
  File "saleor/core/utils/random_data.py", line 638, in create_orders
    order = create_fake_order(discounts)
  File "saleor/core/utils/random_data.py", line 562, in create_fake_order
    create_fake_payment(order=order)
  File "unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "saleor/core/utils/random_data.py", line 429, in create_fake_payment
    payment = create_payment(
  File "saleor/payment/utils.py", line 109, in create_payment
    raise PaymentError(